### ISSUE TITLE
Would you mind uploading your data? The main reason is that the data format is not clear.

### ISSUE THREAD

**Issue by zhiweihu1103** [xiongbo010/ShrinkE#1]
as above

**Comment by Aurora-LiZhi** [comment]
> as above

Hi, I also encountered this problem, the author did not provide data. But have you discovered that the solution is actually very simple?

**Comment by xiongbo010** [comment]
The data structure is the same as https://github.com/migalkin/StarE/tree/master/data. You just need to simply copy them to the folder
